const fs = require('fs');

const questionsEn = [
  // Old Testament - Easy
  { id: "en-ot-e-1", scope: "Old Testament", difficulty: "Easy", question: "Who was the first man created by God?", options: ["Abraham", "Adam", "Moses", "David"], answer: "Adam", explanation: "God created Adam from the dust of the ground.", reference: "Genesis 2:7" },
  { id: "en-ot-e-2", scope: "Old Testament", difficulty: "Easy", question: "Who built the ark to survive the great flood?", options: ["Moses", "Abraham", "Noah", "Joseph"], answer: "Noah", explanation: "God commanded Noah to build an ark to save his family and the animals.", reference: "Genesis 6:14" },
  { id: "en-ot-e-3", scope: "Old Testament", difficulty: "Easy", question: "Who killed Goliath with a sling and a stone?", options: ["Saul", "Jonathan", "Solomon", "David"], answer: "David", explanation: "David, a young shepherd, defeated the Philistine giant Goliath.", reference: "1 Samuel 17:50" },
  { id: "en-ot-e-4", scope: "Old Testament", difficulty: "Easy", question: "What did God use to lead the Israelites out of Egypt?", options: ["A pillar of cloud and fire", "A golden chariot", "A flock of birds", "A majestic lion"], answer: "A pillar of cloud and fire", explanation: "The Lord went ahead of them in a pillar of cloud by day and a pillar of fire by night.", reference: "Exodus 13:21" },
  { id: "en-ot-e-5", scope: "Old Testament", difficulty: "Easy", question: "Who was swallowed by a great fish?", options: ["Jonah", "Peter", "Moses", "Daniel"], answer: "Jonah", explanation: "Jonah was swallowed by a great fish when he tried to flee from God's command.", reference: "Jonah 1:17" },
  
  // Old Testament - Medium
  { id: "en-ot-m-1", scope: "Old Testament", difficulty: "Medium", question: "What was the name of Abraham's first son?", options: ["Isaac", "Ishmael", "Jacob", "Esau"], answer: "Ishmael", explanation: "Ishmael was Abraham's son by Hagar, Sarah's servant.", reference: "Genesis 16:15" },
  { id: "en-ot-m-2", scope: "Old Testament", difficulty: "Medium", question: "Which plague was the final one brought upon Egypt?", options: ["Frogs", "Locusts", "Death of the firstborn", "Water turned to blood"], answer: "Death of the firstborn", explanation: "The tenth and final plague was the death of the firstborn in every Egyptian home.", reference: "Exodus 11:5" },
  { id: "en-ot-m-3", scope: "Old Testament", difficulty: "Medium", question: "Who was the first King of Israel?", options: ["David", "Solomon", "Saul", "Samuel"], answer: "Saul", explanation: "Saul was anointed by Samuel as the first king of Israel.", reference: "1 Samuel 10:1" },
  { id: "en-ot-m-4", scope: "Old Testament", difficulty: "Medium", question: "Which prophet confronted the prophets of Baal on Mount Carmel?", options: ["Elijah", "Elisha", "Isaiah", "Jeremiah"], answer: "Elijah", explanation: "Elijah challenged the prophets of Baal to prove whose God was real.", reference: "1 Kings 18:20-40" },
  { id: "en-ot-m-5", scope: "Old Testament", difficulty: "Medium", question: "Who interpreted Pharaoh's dreams about the famine?", options: ["Daniel", "Moses", "Joseph", "Aaron"], answer: "Joseph", explanation: "Joseph interpreted Pharaoh's dream of seven fat cows and seven skinny cows.", reference: "Genesis 41:25" },

  // Old Testament - Hard
  { id: "en-ot-h-1", scope: "Old Testament", difficulty: "Hard", question: "Who was the oldest man mentioned in the Bible?", options: ["Enoch", "Adam", "Methuselah", "Noah"], answer: "Methuselah", explanation: "Methuselah lived to be 969 years old.", reference: "Genesis 5:27" },
  { id: "en-ot-h-2", scope: "Old Testament", difficulty: "Hard", question: "Who was the father of King Ahab of Israel?", options: ["Omri", "Jeroboam", "Jehu", "Baasha"], answer: "Omri", explanation: "Omri became king of Israel and his son Ahab succeeded him.", reference: "1 Kings 16:28" },
  { id: "en-ot-h-3", scope: "Old Testament", difficulty: "Hard", question: "Which prophet was a herdsman and a dresser of sycamore figs?", options: ["Hosea", "Amos", "Micah", "Joel"], answer: "Amos", explanation: "Amos declared he was neither a prophet nor the son of a prophet, but a herdsman.", reference: "Amos 7:14" },
  { id: "en-ot-h-4", scope: "Old Testament", difficulty: "Hard", question: "What was the name of Moses' Ethiopian (Cushite) wife?", options: ["Zipporah", "Miriam", "Achsah", "The Bible does not name her"], answer: "The Bible does not name her", explanation: "Moses married a Cushite woman, which angered Miriam and Aaron, but she is never named.", reference: "Numbers 12:1" },
  { id: "en-ot-h-5", scope: "Old Testament", difficulty: "Hard", question: "How many years did the Israelites eat manna in the wilderness?", options: ["20", "40", "50", "7"], answer: "40", explanation: "The Israelites ate manna for 40 years until they reached the borders of Canaan.", reference: "Exodus 16:35" },

  // New Testament - Easy
  { id: "en-nt-e-1", scope: "New Testament", difficulty: "Easy", question: "Where was Jesus born?", options: ["Nazareth", "Jerusalem", "Bethlehem", "Galilee"], answer: "Bethlehem", explanation: "Jesus was born in Bethlehem of Judea.", reference: "Matthew 2:1" },
  { id: "en-nt-e-2", scope: "New Testament", difficulty: "Easy", question: "Who baptized Jesus?", options: ["Peter", "John the Baptist", "James", "Matthew"], answer: "John the Baptist", explanation: "Jesus was baptized by John in the Jordan River.", reference: "Matthew 3:13" },
  { id: "en-nt-e-3", scope: "New Testament", difficulty: "Easy", question: "How many disciples did Jesus choose?", options: ["10", "12", "7", "14"], answer: "12", explanation: "Jesus chose twelve disciples to follow Him.", reference: "Luke 6:13" },
  { id: "en-nt-e-4", scope: "New Testament", difficulty: "Easy", question: "Who betrayed Jesus?", options: ["Peter", "Judas Iscariot", "Thomas", "Andrew"], answer: "Judas Iscariot", explanation: "Judas Iscariot betrayed Jesus for thirty pieces of silver.", reference: "Matthew 26:14-16" },
  { id: "en-nt-e-5", scope: "New Testament", difficulty: "Easy", question: "On what day did Jesus rise from the dead?", options: ["The first day", "The third day", "The seventh day", "The tenth day"], answer: "The third day", explanation: "Jesus rose from the dead on the third day.", reference: "Luke 24:7" },

  // New Testament - Medium
  { id: "en-nt-m-1", scope: "New Testament", difficulty: "Medium", question: "What was the profession of Matthew before he followed Jesus?", options: ["Fisherman", "Tax Collector", "Carpenter", "Tentmaker"], answer: "Tax Collector", explanation: "Matthew was sitting at the tax collector's booth when Jesus called him.", reference: "Matthew 9:9" },
  { id: "en-nt-m-2", scope: "New Testament", difficulty: "Medium", question: "At what event did the Holy Spirit descend upon the apostles like tongues of fire?", options: ["The Ascension", "The Transfiguration", "Pentecost", "The Last Supper"], answer: "Pentecost", explanation: "When the day of Pentecost came, they were all filled with the Holy Spirit.", reference: "Acts 2:1-4" },
  { id: "en-nt-m-3", scope: "New Testament", difficulty: "Medium", question: "Who wrote the majority of the Epistles (letters) in the New Testament?", options: ["Peter", "John", "James", "Paul"], answer: "Paul", explanation: "The Apostle Paul wrote 13 of the epistles in the New Testament.", reference: "Various Epistles" },
  { id: "en-nt-m-4", scope: "New Testament", difficulty: "Medium", question: "In what city were the disciples first called 'Christians'?", options: ["Jerusalem", "Rome", "Antioch", "Ephesus"], answer: "Antioch", explanation: "The disciples were called Christians first at Antioch.", reference: "Acts 11:26" },
  { id: "en-nt-m-5", scope: "New Testament", difficulty: "Medium", question: "Who was the High Priest who presided over the trial of Jesus?", options: ["Annas", "Caiaphas", "Pilate", "Herod"], answer: "Caiaphas", explanation: "Those who had arrested Jesus took him to Caiaphas the high priest.", reference: "Matthew 26:57" },

  // New Testament - Hard
  { id: "en-nt-h-1", scope: "New Testament", difficulty: "Hard", question: "To whom did Luke address both his Gospel and the Acts of the Apostles?", options: ["Theophilus", "Cornelius", "Barnabas", "Silas"], answer: "Theophilus", explanation: "Luke addresses both the Gospel of Luke and the Book of Acts to Theophilus.", reference: "Luke 1:3, Acts 1:1" },
  { id: "en-nt-h-2", scope: "New Testament", difficulty: "Hard", question: "Who was the only female judge/prophetess mentioned as serving in the temple when Jesus was presented as a baby?", options: ["Elizabeth", "Mary", "Anna", "Martha"], answer: "Anna", explanation: "Anna, a prophet, the daughter of Penuel, was there when Jesus was presented.", reference: "Luke 2:36" },
  { id: "en-nt-h-3", scope: "New Testament", difficulty: "Hard", question: "What island was Paul shipwrecked on during his journey to Rome?", options: ["Cyprus", "Crete", "Malta", "Patmos"], answer: "Malta", explanation: "Once safely on shore, they found out that the island was called Malta.", reference: "Acts 28:1" },
  { id: "en-nt-h-4", scope: "New Testament", difficulty: "Hard", question: "In the Book of Revelation, which church was described as 'lukewarm'?", options: ["Ephesus", "Smyrna", "Sardis", "Laodicea"], answer: "Laodicea", explanation: "The church in Laodicea was told by Jesus that because they were lukewarm, He would spit them out of His mouth.", reference: "Revelation 3:16" },
  { id: "en-nt-h-5", scope: "New Testament", difficulty: "Hard", question: "Who was chosen to replace Judas Iscariot as the twelfth apostle?", options: ["Barnabas", "Matthias", "Paul", "Stephen"], answer: "Matthias", explanation: "They cast lots, and the lot fell to Matthias; so he was added to the eleven apostles.", reference: "Acts 1:26" },

  // The Gospels - Easy
  { id: "en-gos-e-1", scope: "The Gospels", difficulty: "Easy", question: "Which Gospel is an account of the genealogy, birth, and early life of Jesus designed to prove He was the Messiah to a Jewish audience?", options: ["Mark", "Luke", "John", "Matthew"], answer: "Matthew", explanation: "Matthew's Gospel begins with the genealogy of Jesus, showing his descent from Abraham and David.", reference: "Matthew 1" },
  { id: "en-gos-e-2", scope: "The Gospels", difficulty: "Easy", question: "What was Jesus' first miracle?", options: ["Feeding the 5000", "Walking on water", "Turning water into wine", "Healing a blind man"], answer: "Turning water into wine", explanation: "Jesus turned water into wine at the wedding in Cana of Galilee.", reference: "John 2:1-11" },
  { id: "en-gos-e-3", scope: "The Gospels", difficulty: "Easy", question: "Who were the first two disciples called by Jesus?", options: ["James and John", "Peter and Andrew", "Philip and Bartholomew", "Matthew and Thomas"], answer: "Peter and Andrew", explanation: "As Jesus was walking beside the Sea of Galilee, he saw Simon (Peter) and his brother Andrew casting a net.", reference: "Matthew 4:18" },

  // The Gospels - Medium
  { id: "en-gos-m-1", scope: "The Gospels", difficulty: "Medium", question: "In the Parable of the Sower, what does the seed represent?", options: ["The people", "The Word of God", "Money", "Good deeds"], answer: "The Word of God", explanation: "Jesus explained that the seed is the word of God.", reference: "Luke 8:11" },
  { id: "en-gos-m-2", scope: "The Gospels", difficulty: "Medium", question: "Who climbed a sycamore-fig tree to see Jesus in Jericho?", options: ["Nicodemus", "Bartimaeus", "Zacchaeus", "Lazarus"], answer: "Zacchaeus", explanation: "Zacchaeus was a short man and climbed a tree to see Jesus passing by.", reference: "Luke 19:4" },
  { id: "en-gos-m-3", scope: "The Gospels", difficulty: "Medium", question: "Which Gospel is NOT considered one of the 'Synoptic Gospels'?", options: ["Matthew", "Mark", "Luke", "John"], answer: "John", explanation: "Matthew, Mark, and Luke are the Synoptic Gospels because they include many of the same stories, often in a similar sequence.", reference: "Biblical study" },

  // The Gospels - Hard
  { id: "en-gos-h-1", scope: "The Gospels", difficulty: "Hard", question: "In John's Gospel, Jesus makes seven 'I am' statements. Which of these is NOT one of them?", options: ["I am the bread of life", "I am the light of the world", "I am the great physician", "I am the good shepherd"], answer: "I am the great physician", explanation: "While Jesus is a healer, 'I am the great physician' is not one of the specific 'I am' statements in John.", reference: "Book of John" },
  { id: "en-gos-h-2", scope: "The Gospels", difficulty: "Hard", question: "To whom did Jesus say, 'Very truly I tell you, no one can see the kingdom of God unless they are born again'?", options: ["Peter", "Nicodemus", "The Samaritan Woman", "Mary Magdalene"], answer: "Nicodemus", explanation: "Jesus spoke these words to Nicodemus, a Pharisee who came to Him at night.", reference: "John 3:3" },
  { id: "en-gos-h-3", scope: "The Gospels", difficulty: "Hard", question: "In the Sermon on the Mount, Jesus said 'Blessed are the meek...'. What is the promise given to them?", options: ["They will see God", "They will inherit the earth", "They will be called children of God", "Theirs is the kingdom of heaven"], answer: "They will inherit the earth", explanation: "Blessed are the meek, for they will inherit the earth.", reference: "Matthew 5:5" }
];

const questionsFr = [
  // Ancien Testament - Facile
  { id: "fr-ot-e-1", scope: "Old Testament", difficulty: "Easy", question: "Qui a été le premier homme créé par Dieu ?", options: ["Abraham", "Adam", "Moïse", "David"], answer: "Adam", explanation: "Dieu a créé Adam à partir de la poussière du sol.", reference: "Genèse 2:7" },
  { id: "fr-ot-e-2", scope: "Old Testament", difficulty: "Easy", question: "Qui a construit l'arche pour survivre au grand déluge ?", options: ["Moïse", "Abraham", "Noé", "Joseph"], answer: "Noé", explanation: "Dieu a commandé à Noé de construire une arche pour sauver sa famille et les animaux.", reference: "Genèse 6:14" },
  { id: "fr-ot-e-3", scope: "Old Testament", difficulty: "Easy", question: "Qui a tué Goliath avec une fronde et une pierre ?", options: ["Saül", "Jonathan", "Salomon", "David"], answer: "David", explanation: "David, un jeune berger, a vaincu le géant philistin Goliath.", reference: "1 Samuel 17:50" },
  { id: "fr-ot-e-4", scope: "Old Testament", difficulty: "Easy", question: "Qu'est-ce que Dieu a utilisé pour guider les Israélites hors d'Égypte ?", options: ["Une colonne de nuée et de feu", "Un char d'or", "Une volée d'oiseaux", "Un lion majestueux"], answer: "Une colonne de nuée et de feu", explanation: "L'Éternel allait devant eux le jour dans une colonne de nuée et la nuit dans une colonne de feu.", reference: "Exode 13:21" },
  { id: "fr-ot-e-5", scope: "Old Testament", difficulty: "Easy", question: "Qui a été avalé par un grand poisson ?", options: ["Jonas", "Pierre", "Moïse", "Daniel"], answer: "Jonas", explanation: "Jonas a été avalé par un grand poisson lorsqu'il a tenté de fuir l'ordre de Dieu.", reference: "Jonas 1:17" },

  // Ancien Testament - Moyen
  { id: "fr-ot-m-1", scope: "Old Testament", difficulty: "Medium", question: "Quel était le nom du premier fils d'Abraham ?", options: ["Isaac", "Ismaël", "Jacob", "Ésaü"], answer: "Ismaël", explanation: "Ismaël était le fils d'Abraham par Agar, la servante de Sara.", reference: "Genèse 16:15" },
  { id: "fr-ot-m-2", scope: "Old Testament", difficulty: "Medium", question: "Quelle a été la dernière plaie envoyée sur l'Égypte ?", options: ["Les grenouilles", "Les sauterelles", "La mort des premiers-nés", "L'eau changée en sang"], answer: "La mort des premiers-nés", explanation: "La dixième et dernière plaie a été la mort du premier-né dans chaque foyer égyptien.", reference: "Exode 11:5" },
  { id: "fr-ot-m-3", scope: "Old Testament", difficulty: "Medium", question: "Qui fut le premier roi d'Israël ?", options: ["David", "Salomon", "Saül", "Samuel"], answer: "Saül", explanation: "Saül fut oint par Samuel comme le premier roi d'Israël.", reference: "1 Samuel 10:1" },
  { id: "fr-ot-m-4", scope: "Old Testament", difficulty: "Medium", question: "Quel prophète a affronté les prophètes de Baal sur le mont Carmel ?", options: ["Élie", "Élisée", "Ésaïe", "Jérémie"], answer: "Élie", explanation: "Élie a mis au défi les prophètes de Baal pour prouver quel Dieu était réel.", reference: "1 Rois 18:20-40" },
  { id: "fr-ot-m-5", scope: "Old Testament", difficulty: "Medium", question: "Qui a interprété les rêves de Pharaon concernant la famine ?", options: ["Daniel", "Moïse", "Joseph", "Aaron"], answer: "Joseph", explanation: "Joseph a interprété le rêve de Pharaon concernant sept vaches grasses et sept vaches maigres.", reference: "Genèse 41:25" },

  // Ancien Testament - Difficile
  { id: "fr-ot-h-1", scope: "Old Testament", difficulty: "Hard", question: "Qui est l'homme le plus âgé mentionné dans la Bible ?", options: ["Hénoc", "Adam", "Metuschélah", "Noé"], answer: "Metuschélah", explanation: "Metuschélah (Mathusalem) a vécu jusqu'à l'âge de 969 ans.", reference: "Genèse 5:27" },
  { id: "fr-ot-h-2", scope: "Old Testament", difficulty: "Hard", question: "Qui était le père du roi Achab d'Israël ?", options: ["Omri", "Jéroboam", "Jéhu", "Baescha"], answer: "Omri", explanation: "Omri devint roi d'Israël et son fils Achab lui succéda.", reference: "1 Rois 16:28" },
  { id: "fr-ot-h-3", scope: "Old Testament", difficulty: "Hard", question: "Quel prophète était berger et cultivait des sycomores ?", options: ["Osée", "Amos", "Michée", "Joël"], answer: "Amos", explanation: "Amos déclara qu'il n'était ni prophète ni fils de prophète, mais berger.", reference: "Amos 7:14" },
  { id: "fr-ot-h-4", scope: "Old Testament", difficulty: "Hard", question: "Quel était le nom de la femme éthiopienne (Cuschite) de Moïse ?", options: ["Séphora", "Myriam", "Acsah", "La Bible ne la nomme pas"], answer: "La Bible ne la nomme pas", explanation: "Moïse épousa une femme cuschite, ce qui irrita Myriam et Aaron, mais elle n'est jamais nommée.", reference: "Nombres 12:1" },
  { id: "fr-ot-h-5", scope: "Old Testament", difficulty: "Hard", question: "Pendant combien d'années les Israélites ont-ils mangé de la manne dans le désert ?", options: ["20", "40", "50", "7"], answer: "40", explanation: "Les Israélites mangèrent de la manne pendant 40 ans, jusqu'à leur arrivée aux frontières de Canaan.", reference: "Exode 16:35" },

  // Nouveau Testament - Facile
  { id: "fr-nt-e-1", scope: "New Testament", difficulty: "Easy", question: "Où Jésus est-il né ?", options: ["Nazareth", "Jérusalem", "Bethléem", "Galilée"], answer: "Bethléem", explanation: "Jésus est né à Bethléem en Judée.", reference: "Matthieu 2:1" },
  { id: "fr-nt-e-2", scope: "New Testament", difficulty: "Easy", question: "Qui a baptisé Jésus ?", options: ["Pierre", "Jean-Baptiste", "Jacques", "Matthieu"], answer: "Jean-Baptiste", explanation: "Jésus fut baptisé par Jean dans le fleuve Jourdain.", reference: "Matthieu 3:13" },
  { id: "fr-nt-e-3", scope: "New Testament", difficulty: "Easy", question: "Combien de disciples Jésus a-t-il choisis ?", options: ["10", "12", "7", "14"], answer: "12", explanation: "Jésus a choisi douze disciples pour le suivre.", reference: "Luc 6:13" },
  { id: "fr-nt-e-4", scope: "New Testament", difficulty: "Easy", question: "Qui a trahi Jésus ?", options: ["Pierre", "Judas Iscariot", "Thomas", "André"], answer: "Judas Iscariot", explanation: "Judas Iscariot a trahi Jésus pour trente pièces d'argent.", reference: "Matthieu 26:14-16" },
  { id: "fr-nt-e-5", scope: "New Testament", difficulty: "Easy", question: "Quel jour Jésus est-il ressuscité des morts ?", options: ["Le premier jour", "Le troisième jour", "Le septième jour", "Le dixième jour"], answer: "Le troisième jour", explanation: "Jésus est ressuscité des morts le troisième jour.", reference: "Luc 24:7" },

  // Nouveau Testament - Moyen
  { id: "fr-nt-m-1", scope: "New Testament", difficulty: "Medium", question: "Quelle était la profession de Matthieu avant de suivre Jésus ?", options: ["Pêcheur", "Collecteur d'impôts", "Charpentier", "Faiseur de tentes"], answer: "Collecteur d'impôts", explanation: "Matthieu était assis au bureau des péages lorsque Jésus l'a appelé.", reference: "Matthieu 9:9" },
  { id: "fr-nt-m-2", scope: "New Testament", difficulty: "Medium", question: "Lors de quel événement le Saint-Esprit est-il descendu sur les apôtres comme des langues de feu ?", options: ["L'Ascension", "La Transfiguration", "La Pentecôte", "La Cène"], answer: "La Pentecôte", explanation: "Le jour de la Pentecôte, ils furent tous remplis du Saint-Esprit.", reference: "Actes 2:1-4" },
  { id: "fr-nt-m-3", scope: "New Testament", difficulty: "Medium", question: "Qui a écrit la majorité des Épîtres (lettres) dans le Nouveau Testament ?", options: ["Pierre", "Jean", "Jacques", "Paul"], answer: "Paul", explanation: "L'apôtre Paul a écrit 13 des épîtres du Nouveau Testament.", reference: "Diverses Épîtres" },
  { id: "fr-nt-m-4", scope: "New Testament", difficulty: "Medium", question: "Dans quelle ville les disciples furent-ils appelés 'Chrétiens' pour la première fois ?", options: ["Jérusalem", "Rome", "Antioche", "Éphèse"], answer: "Antioche", explanation: "Ce fut à Antioche que, pour la première fois, les disciples furent appelés chrétiens.", reference: "Actes 11:26" },
  { id: "fr-nt-m-5", scope: "New Testament", difficulty: "Medium", question: "Qui était le souverain sacrificateur qui a présidé le procès de Jésus ?", options: ["Anne", "Caïphe", "Pilate", "Hérode"], answer: "Caïphe", explanation: "Ceux qui avaient saisi Jésus l'emmenèrent chez Caïphe, le souverain sacrificateur.", reference: "Matthieu 26:57" },

  // Nouveau Testament - Difficile
  { id: "fr-nt-h-1", scope: "New Testament", difficulty: "Hard", question: "À qui Luc a-t-il adressé à la fois son Évangile et les Actes des Apôtres ?", options: ["Théophile", "Corneille", "Barnabas", "Silas"], answer: "Théophile", explanation: "Luc adresse l'Évangile de Luc et le livre des Actes à Théophile.", reference: "Luc 1:3, Actes 1:1" },
  { id: "fr-nt-h-2", scope: "New Testament", difficulty: "Hard", question: "Qui était la seule femme juge/prophétesse mentionnée comme servant dans le temple lorsque Jésus fut présenté au temple comme bébé ?", options: ["Élisabeth", "Marie", "Anne", "Marthe"], answer: "Anne", explanation: "Anne, une prophétesse, fille de Phanuel, était là lorsque Jésus fut présenté.", reference: "Luc 2:36" },
  { id: "fr-nt-h-3", scope: "New Testament", difficulty: "Hard", question: "Sur quelle île Paul a-t-il fait naufrage lors de son voyage vers Rome ?", options: ["Chypre", "Crète", "Malte", "Patmos"], answer: "Malte", explanation: "Une fois sauvés, ils apprirent que l'île s'appelait Malte.", reference: "Actes 28:1" },
  { id: "fr-nt-h-4", scope: "New Testament", difficulty: "Hard", question: "Dans le livre de l'Apocalypse, quelle église est décrite comme 'tiède' ?", options: ["Éphèse", "Smyrne", "Sardes", "Laodicée"], answer: "Laodicée", explanation: "Jésus a dit à l'église de Laodicée que, puisqu'elle était tiède, Il la vomirait de Sa bouche.", reference: "Apocalypse 3:16" },
  { id: "fr-nt-h-5", scope: "New Testament", difficulty: "Hard", question: "Qui a été choisi pour remplacer Judas Iscariot comme douzième apôtre ?", options: ["Barnabas", "Matthias", "Paul", "Étienne"], answer: "Matthias", explanation: "Ils tirèrent au sort, et le sort tomba sur Matthias, qui fut associé aux onze apôtres.", reference: "Actes 1:26" },

  // Les Évangiles - Facile
  { id: "fr-gos-e-1", scope: "The Gospels", difficulty: "Easy", question: "Quel Évangile est un récit de la généalogie, de la naissance et des débuts de la vie de Jésus, conçu pour prouver qu'Il était le Messie à un public juif ?", options: ["Marc", "Luc", "Jean", "Matthieu"], answer: "Matthieu", explanation: "L'Évangile de Matthieu commence par la généalogie de Jésus, montrant sa descendance d'Abraham et de David.", reference: "Matthieu 1" },
  { id: "fr-gos-e-2", scope: "The Gospels", difficulty: "Easy", question: "Quel a été le premier miracle de Jésus ?", options: ["Nourrir les 5000", "Marcher sur l'eau", "Changer l'eau en vin", "Guérir un aveugle"], answer: "Changer l'eau en vin", explanation: "Jésus a changé l'eau en vin lors des noces de Cana en Galilée.", reference: "Jean 2:1-11" },
  { id: "fr-gos-e-3", scope: "The Gospels", difficulty: "Easy", question: "Quels furent les deux premiers disciples appelés par Jésus ?", options: ["Jacques et Jean", "Pierre et André", "Philippe et Barthélemy", "Matthieu et Thomas"], answer: "Pierre et André", explanation: "Comme Jésus marchait le long de la mer de Galilée, il vit Simon (Pierre) et son frère André jeter un filet.", reference: "Matthieu 4:18" },

  // Les Évangiles - Moyen
  { id: "fr-gos-m-1", scope: "The Gospels", difficulty: "Medium", question: "Dans la parabole du semeur, que représente la semence ?", options: ["Le peuple", "La Parole de Dieu", "L'argent", "Les bonnes œuvres"], answer: "La Parole de Dieu", explanation: "Jésus a expliqué que la semence est la parole de Dieu.", reference: "Luc 8:11" },
  { id: "fr-gos-m-2", scope: "The Gospels", difficulty: "Medium", question: "Qui est monté sur un mûrier sycomore pour voir Jésus à Jéricho ?", options: ["Nicodème", "Bartimée", "Zachée", "Lazare"], answer: "Zachée", explanation: "Zachée était un homme de petite taille et est monté dans un arbre pour voir Jésus passer.", reference: "Luc 19:4" },
  { id: "fr-gos-m-3", scope: "The Gospels", difficulty: "Medium", question: "Quel Évangile n'est PAS considéré comme l'un des 'Évangiles Synoptiques' ?", options: ["Matthieu", "Marc", "Luc", "Jean"], answer: "Jean", explanation: "Matthieu, Marc et Luc sont les évangiles synoptiques, car ils incluent plusieurs des mêmes histoires, souvent dans une séquence similaire.", reference: "Étude Biblique" },

  // Les Évangiles - Difficile
  { id: "fr-gos-h-1", scope: "The Gospels", difficulty: "Hard", question: "Dans l'Évangile de Jean, Jésus fait sept déclarations 'Je suis'. Laquelle n'en fait PAS partie ?", options: ["Je suis le pain de vie", "Je suis la lumière du monde", "Je suis le grand médecin", "Je suis le bon berger"], answer: "Je suis le grand médecin", explanation: "Bien que Jésus soit un guérisseur, 'Je suis le grand médecin' n'est pas l'une des déclarations spécifiques 'Je suis' dans Jean.", reference: "Livre de Jean" },
  { id: "fr-gos-h-2", scope: "The Gospels", difficulty: "Hard", question: "À qui Jésus a-t-il dit : 'En vérité, en vérité, je te le dis, si un homme ne naît de nouveau, il ne peut voir le royaume de Dieu' ?", options: ["Pierre", "Nicodème", "La femme samaritaine", "Marie de Magdala"], answer: "Nicodème", explanation: "Jésus a prononcé ces mots à Nicodème, un pharisien venu Le voir de nuit.", reference: "Jean 3:3" },
  { id: "fr-gos-h-3", scope: "The Gospels", difficulty: "Hard", question: "Dans le Sermon sur la Montagne, Jésus a dit 'Heureux les débonnaires...'. Quelle est la promesse qui leur est donnée ?", options: ["Ils verront Dieu", "Ils hériteront de la terre", "Ils seront appelés fils de Dieu", "Le royaume des cieux est à eux"], answer: "Ils hériteront de la terre", explanation: "Heureux les débonnaires, car ils hériteront la terre.", reference: "Matthieu 5:5" }
];

fs.writeFileSync('src/data/quiz-en.json', JSON.stringify(questionsEn, null, 2));
fs.writeFileSync('src/data/quiz-fr.json', JSON.stringify(questionsFr, null, 2));

console.log('Quiz data generated successfully');
